version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - JamsRepos
      - PhantomMantis
      - MrDynamo
    target-branch: "develop"

  - package-ecosystem: "pip"
    directory: "/apps/wizarr-backend/"
    schedule:
      interval: "daily"
    reviewers:
      - JamsRepos
      - PhantomMantis
      - MrDynamo
    target-branch: "develop"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - JamsRepos
      - PhantomMantis
      - MrDynamo
    target-branch: "develop"
