name: CI/CD Build Image

on:
  workflow_dispatch:  # Enables manual trigger from GitHub Actions UI
    inputs:
      tag:
        description: "Image tag (e.g., v1.0.0 or latest)"
        required: true
        default: "latest"

permissions:
  packages: write
  contents: read

env:
  GHCR_REGISTRY: ghcr.io
  IMAGE_NAME: alexjyong/wizarr

jobs:
  build_and_push:
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to GitHub Container Registry (GHCR)
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push image
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfiles/wizarr-ci/Dockerfile
          push: true
          tags: |
            ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.tag }}
            ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
